/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-09-30 03:16:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.decorators;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class web_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/commons/taglib.jsp", Long.valueOf(1727054983723L));
    _jspx_dependants.put("jar:file:/C:/Users/thang/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("/commons/web/brand.jsp", Long.valueOf(1727055285060L));
    _jspx_dependants.put("/commons/web/step.jsp", Long.valueOf(1727053191846L));
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1725849407127L));
    _jspx_dependants.put("/commons/web/slider.jsp", Long.valueOf(1727055301510L));
    _jspx_dependants.put("/commons/web/header.jsp", Long.valueOf(1727061095452L));
    _jspx_dependants.put("/commons/web/footer.jsp", Long.valueOf(1727055285055L));
    _jspx_dependants.put("jar:file:/C:/Users/thang/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>Metronic Shop UI</title>\r\n");
      out.write("\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("    <meta content=\"Metronic Shop UI description\" name=\"description\">\r\n");
      out.write("    <meta content=\"Metronic Shop UI keywords\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"keenthemes\" name=\"author\">\r\n");
      out.write("\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("    <meta property=\"og:title\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("    <meta property=\"og:description\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("    <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"-CUSTOMER VALUE-\"><!-- link to image for socio -->\r\n");
      out.write("    <meta property=\"og:url\" content=\"-CUSTOMER VALUE-\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Fonts START -->\r\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700|PT+Sans+Narrow|Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900&amp;subset=all\" rel=\"stylesheet\" type=\"text/css\"><!--- fonts for slider on the index page -->\r\n");
      out.write("    <!-- Fonts END -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Global styles START -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Global styles END -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugin styles START -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/fancybox/source/jquery.fancybox.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/carousel-owl-carousel/owl-carousel/owl.carousel.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/slider-layer-slider/css/layerslider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/uniform/css/uniform.default.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <!-- Page level plugin styles END -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Theme styles START -->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/css/components.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/css/style-shop.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/css/style-layer-slider.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/style-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/themes/red.css\" rel=\"stylesheet\" id=\"style-color\">\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Theme styles END -->\r\n");
      out.write("</head>\r\n");
      out.write("<!-- Head END -->\r\n");
      out.write("\r\n");
      out.write("<!-- Body BEGIN -->\r\n");
      out.write("<body class=\"ecommerce\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN HEADER -->\r\n");
      out.write("    ");
      out.write("<!-- BEGIN TOP BAR -->\r\n");
      out.write("<div class=\"pre-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- BEGIN TOP BAR LEFT PART -->\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 additional-shop-info\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline\">\r\n");
      out.write("                    <li><i class=\"fa fa-phone\"></i><span>+1 456 6717</span></li>\r\n");
      out.write("                    <!-- BEGIN CURRENCIES -->\r\n");
      out.write("                    <li class=\"shop-currencies\">\r\n");
      out.write("                        <a href=\"javascript:void(0);\">â¬</a>\r\n");
      out.write("                        <a href=\"javascript:void(0);\">Â£</a>\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"current\">$</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <!-- END CURRENCIES -->\r\n");
      out.write("                    <!-- BEGIN LANGS -->\r\n");
      out.write("                    <li class=\"langs-block\">\r\n");
      out.write("                        <a href=\"javascript:void(0);\" class=\"current\">English </a>\r\n");
      out.write("                        <div class=\"langs-block-others-wrapper\"><div class=\"langs-block-others\">\r\n");
      out.write("                            <a href=\"javascript:void(0);\">French</a>\r\n");
      out.write("                            <a href=\"javascript:void(0);\">Germany</a>\r\n");
      out.write("                            <a href=\"javascript:void(0);\">Turkish</a>\r\n");
      out.write("                        </div></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <!-- END LANGS -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END TOP BAR LEFT PART -->\r\n");
      out.write("            <!-- BEGIN TOP BAR MENU -->\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 additional-nav\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline pull-right\">\r\n");
      out.write("                    <li><a href=\"shop-account.html\">My Account</a></li>\r\n");
      out.write("                    <li><a href=\"shop-wishlist.html\">My Wishlist</a></li>\r\n");
      out.write("                    <li><a href=\"shop-checkout.html\">Checkout</a></li>\r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END TOP BAR MENU -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END TOP BAR -->\r\n");
      out.write("<!-- BEGIN HEADER -->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"site-logo\" href=\"shop-index.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/img/logos/logo-shop-red.png\" alt=\"Metronic Shop UI\"></a>\r\n");
      out.write("\r\n");
      out.write("        <a href=\"javascript:void(0);\" class=\"mobi-toggler\"><i class=\"fa fa-bars\"></i></a>\r\n");
      out.write("\r\n");
      out.write("        <!-- BEGIN CART -->\r\n");
      out.write("        <div class=\"top-cart-block\">\r\n");
      out.write("            <div class=\"top-cart-info\">\r\n");
      out.write("                <a href=\"javascript:void(0);\" class=\"top-cart-info-count\">3 items</a>\r\n");
      out.write("                <a href=\"javascript:void(0);\" class=\"top-cart-info-value\">$1260</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <i class=\"fa fa-shopping-cart\"></i>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"top-cart-content-wrapper\">\r\n");
      out.write("                <div class=\"top-cart-content\">\r\n");
      out.write("                    <ul class=\"scroller\" style=\"height: 250px;\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/cart-img.jpg\" alt=\"Rolex Classic Watch\" width=\"37\" height=\"34\"></a>\r\n");
      out.write("                            <span class=\"cart-content-count\">x 1</span>\r\n");
      out.write("                            <strong><a href=\"shop-item.html\">Rolex Classic Watch</a></strong>\r\n");
      out.write("                            <em>$1230</em>\r\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"del-goods\">&nbsp;</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"text-right\">\r\n");
      out.write("                        <a href=\"shop-shopping-cart.html\" class=\"btn btn-default\">View Cart</a>\r\n");
      out.write("                        <a href=\"shop-checkout.html\" class=\"btn btn-primary\">Checkout</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--END CART -->\r\n");
      out.write("\r\n");
      out.write("        <!-- BEGIN NAVIGATION -->\r\n");
      out.write("        <div class=\"header-navigation\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-target=\"#\" href=\"#\">\r\n");
      out.write("                        Woman\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <!-- BEGIN DROPDOWN MENU -->\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li class=\"dropdown-submenu\">\r\n");
      out.write("                            <a href=\"shop-product-list.html\">Hi Tops <i class=\"fa fa-angle-right\"></i></a>\r\n");
      out.write("                            <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("                                <li><a href=\"shop-product-list.html\">Second Level Link</a></li>\r\n");
      out.write("                                <li><a href=\"shop-product-list.html\">Second Level Link</a></li>\r\n");
      out.write("                                <li class=\"dropdown-submenu\">\r\n");
      out.write("                                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-target=\"#\" href=\"#\">\r\n");
      out.write("                                        Second Level Link\r\n");
      out.write("                                        <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                                        <li><a href=\"shop-product-list.html\">Third Level Link</a></li>\r\n");
      out.write("                                        <li><a href=\"shop-product-list.html\">Third Level Link</a></li>\r\n");
      out.write("                                        <li><a href=\"shop-product-list.html\">Third Level Link</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-product-list.html\">Running Shoes</a></li>\r\n");
      out.write("                        <li><a href=\"shop-product-list.html\">Jackets and Coats</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <!-- END DROPDOWN MENU -->\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown dropdown-megamenu\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-target=\"#\" href=\"#\">\r\n");
      out.write("                        Man\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"header-navigation-content\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-4 header-navigation-col\">\r\n");
      out.write("                                        <h4>Footwear</h4>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Astro Trainers</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Basketball Shoes</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Boots</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Canvas Shoes</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Football Boots</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Golf Shoes</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Hi Tops</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Indoor and Court Trainers</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-4 header-navigation-col\">\r\n");
      out.write("                                        <h4>Clothing</h4>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Base Layer</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Character</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Chinos</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Combats</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Cricket Clothing</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Fleeces</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Gilets</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Golf Tops</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-4 header-navigation-col\">\r\n");
      out.write("                                        <h4>Accessories</h4>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Belts</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Caps</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Gloves, Hats and Scarves</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("\r\n");
      out.write("                                        <h4>Clearance</h4>\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Jackets</a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\">Bottoms</a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-12 nav-brands\">\r\n");
      out.write("                                        <ul>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\"><img title=\"esprit\" alt=\"esprit\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/esprit.jpg\"></a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\"><img title=\"gap\" alt=\"gap\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/gap.jpg\"></a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\"><img title=\"next\" alt=\"next\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/next.jpg\"></a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\"><img title=\"puma\" alt=\"puma\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/puma.jpg\"></a></li>\r\n");
      out.write("                                            <li><a href=\"shop-product-list.html\"><img title=\"zara\" alt=\"zara\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/zara.jpg\"></a></li>\r\n");
      out.write("                                        </ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"shop-item.html\">Kids</a></li>\r\n");
      out.write("                <li class=\"dropdown dropdown100 nav-catalogue\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-target=\"#\" href=\"#\">\r\n");
      out.write("                        New\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <div class=\"header-navigation-content\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("                                        <div class=\"product-item\">\r\n");
      out.write("                                            <div class=\"pi-img-wrapper\">\r\n");
      out.write("                                                <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                                            <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("                                        <div class=\"product-item\">\r\n");
      out.write("                                            <div class=\"pi-img-wrapper\">\r\n");
      out.write("                                                <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                                            <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("                                        <div class=\"product-item\">\r\n");
      out.write("                                            <div class=\"pi-img-wrapper\">\r\n");
      out.write("                                                <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model7.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                                            <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-md-3 col-sm-4 col-xs-6\">\r\n");
      out.write("                                        <div class=\"product-item\">\r\n");
      out.write("                                            <div class=\"pi-img-wrapper\">\r\n");
      out.write("                                                <a href=\"shop-item.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\"></a>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                                            <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                                            <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"dropdown active\">\r\n");
      out.write("                    <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" data-target=\"#\" href=\"#\">\r\n");
      out.write("                        Pages\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <li><a href=\"shop-index.html\">Home Default</a></li>\r\n");
      out.write("                        <li class=\"active\"><a href=\"shop-index-header-fix.html\">Home Header Fixed</a></li>\r\n");
      out.write("                        <li><a href=\"shop-index-light-footer.html\">Home Light Footer</a></li>\r\n");
      out.write("                        <li><a href=\"shop-product-list.html\">Product List</a></li>\r\n");
      out.write("                        <li><a href=\"shop-search-result.html\">Search Result</a></li>\r\n");
      out.write("                        <li><a href=\"shop-item.html\">Product Page</a></li>\r\n");
      out.write("                        <li><a href=\"shop-shopping-cart-null.html\">Shopping Cart (Null Cart)</a></li>\r\n");
      out.write("                        <li><a href=\"shop-shopping-cart.html\">Shopping Cart</a></li>\r\n");
      out.write("                        <li><a href=\"shop-checkout.html\">Checkout</a></li>\r\n");
      out.write("                        <li><a href=\"shop-about.html\">About</a></li>\r\n");
      out.write("                        <li><a href=\"shop-contacts.html\">Contacts</a></li>\r\n");
      out.write("                        <li><a href=\"shop-account.html\">My account</a></li>\r\n");
      out.write("                        <li><a href=\"shop-wishlist.html\">My Wish List</a></li>\r\n");
      out.write("                        <li><a href=\"shop-goods-compare.html\">Product Comparison</a></li>\r\n");
      out.write("                        <li><a href=\"shop-standart-forms.html\">Standart Forms</a></li>\r\n");
      out.write("                        <li><a href=\"shop-faq.html\">FAQ</a></li>\r\n");
      out.write("                        <li><a href=\"shop-privacy-policy.html\">Privacy Policy</a></li>\r\n");
      out.write("                        <li><a href=\"shop-terms-conditions-page.html\">Terms &amp; Conditions</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li><a href=\"index.html\" target=\"_blank\">Corporate</a></li>\r\n");
      out.write("                <li><a href=\"onepage-index.html\" target=\"_blank\">One Page</a></li>\r\n");
      out.write("                <li><a href=\"http://keenthemes.com/preview/metronic/theme/templates/admin&amp;page=ecommerce_index.html\" target=\"_blank\">Admin theme</a></li>\r\n");
      out.write("\r\n");
      out.write("                <!-- BEGIN TOP SEARCH -->\r\n");
      out.write("                <li class=\"menu-search\">\r\n");
      out.write("                    <span class=\"sep\"></span>\r\n");
      out.write("                    <i class=\"fa fa-search search-btn\"></i>\r\n");
      out.write("                    <div class=\"search-box\">\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <input type=\"text\" placeholder=\"Search\" class=\"form-control\">\r\n");
      out.write("                                <span class=\"input-group-btn\">\r\n");
      out.write("                      <button class=\"btn btn-primary\" type=\"submit\">Search</button>\r\n");
      out.write("                    </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <!-- END TOP SEARCH -->\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- END NAVIGATION -->\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Header END -->");
      out.write("\r\n");
      out.write("<!-- END HEADER -->\r\n");
      out.write("<!-- BEGIN SLIDER -->\r\n");
      out.write("    ");
      out.write("<!-- BEGIN SLIDER -->\r\n");
      out.write("<div class=\"page-slider margin-bottom-35\">\r\n");
      out.write("    <!-- LayerSlider start -->\r\n");
      out.write("    <div id=\"layerslider\" style=\"width: 100%; height: 494px; margin: 0 auto;\">\r\n");
      out.write("\r\n");
      out.write("        <!-- slide one start -->\r\n");
      out.write("        <div class=\"ls-slide ls-slide1\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 24,25,27,28;\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide1/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ls-l ls-title\" style=\"top: 96px; left: 35%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("            fade: true;\r\n");
      out.write("            fadeout: true;\r\n");
      out.write("            durationin: 750;\r\n");
      out.write("            durationout: 750;\r\n");
      out.write("            easingin: easeOutQuint;\r\n");
      out.write("            rotatein: 90;\r\n");
      out.write("            rotateout: -90;\r\n");
      out.write("            scalein: .5;\r\n");
      out.write("            scaleout: .5;\r\n");
      out.write("            showuntil: 4000;\r\n");
      out.write("          \">Tones of <strong>shop UI features</strong> designed</div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ls-l ls-mini-text\" style=\"top: 338px; left: 35%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationout: 750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          delayin: 300;\r\n");
      out.write("          showuntil: 4000;\r\n");
      out.write("          \">Lorem ipsum dolor sit amet  constectetuer diam<br > adipiscing elit euismod ut laoreet dolore.\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- slide one end -->\r\n");
      out.write("\r\n");
      out.write("        <!-- slide two start -->\r\n");
      out.write("        <div class=\"ls-slide ls-slide2\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 110,111,112,113;\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide2/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ls-l ls-title\" style=\"top: 40%; left: 21%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationin: 750; durationout: 109750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          easingout: easeInOutQuint;\r\n");
      out.write("          delayin: 0;\r\n");
      out.write("          delayout: 0;\r\n");
      out.write("          rotatein: 90;\r\n");
      out.write("          rotateout: -90;\r\n");
      out.write("          scalein: .5;\r\n");
      out.write("          scaleout: .5;\r\n");
      out.write("          showuntil: 4000;\r\n");
      out.write("          \"><strong>Unlimted</strong> Layout Options <em>Fully Responsive</em>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ls-l ls-price\" style=\"top: 50%; left: 45%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationout: 109750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          delayin: 300;\r\n");
      out.write("          scalein: .8;\r\n");
      out.write("          scaleout: .8;\r\n");
      out.write("          showuntil: 4000;\"><b>from</b> <strong><span>$</span>25</strong>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <a href=\"#\" class=\"ls-l ls-more\" style=\"top: 72%; left: 21%; display: inline-block; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationin: 750;\r\n");
      out.write("          durationout: 750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          easingout: easeInOutQuint;\r\n");
      out.write("          delayin: 0;\r\n");
      out.write("          delayout: 0;\r\n");
      out.write("          rotatein: 90;\r\n");
      out.write("          rotateout: -90;\r\n");
      out.write("          scalein: .5;\r\n");
      out.write("          scaleout: .5;\r\n");
      out.write("          showuntil: 4000;\">See More Details\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- slide two end -->\r\n");
      out.write("\r\n");
      out.write("        <!-- slide three start -->\r\n");
      out.write("        <div class=\"ls-slide ls-slide3\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 92,93,105;\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide3/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ls-l ls-title\" style=\"top: 83px; left: 33%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationin: 750;\r\n");
      out.write("          durationout: 750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          rotatein: 90;\r\n");
      out.write("          rotateout: -90;\r\n");
      out.write("          scalein: .5;\r\n");
      out.write("          scaleout: .5;\r\n");
      out.write("          showuntil: 4000;\r\n");
      out.write("          \">Full Admin &amp; Frontend <strong>eCommerce UI</strong> Is Ready For Your Project\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ls-l\" style=\"top: 333px; left: 33%; white-space: nowrap; font-size: 20px; font: 20px 'Open Sans Light', sans-serif;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationout: 750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          delayin: 300;\r\n");
      out.write("          scalein: .8;\r\n");
      out.write("          scaleout: .8;\r\n");
      out.write("          showuntil: 4000;\r\n");
      out.write("          \">\r\n");
      out.write("                <a href=\"#\" class=\"ls-buy\">\r\n");
      out.write("                    Buy It Now!\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"ls-price\">\r\n");
      out.write("                    <span>All these for only:</span>\r\n");
      out.write("                    <strong>25<sup>$</sup></strong>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- slide three end -->\r\n");
      out.write("\r\n");
      out.write("        <!-- slide four start -->\r\n");
      out.write("        <div class=\"ls-slide ls-slide4\" data-ls=\"offsetxin: right; slidedelay: 7000; transition2d: 110,111,112,113;\">\r\n");
      out.write("\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/layerslider/slide5/bg.jpg\" class=\"ls-bg\" alt=\"Slide background\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ls-l ls-title\" style=\"top: 35%; left: 60%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationin: 750;\r\n");
      out.write("          durationout: 750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          rotatein: 90;\r\n");
      out.write("          rotateout: -90;\r\n");
      out.write("          scalein: .5;\r\n");
      out.write("          scaleout: .5;\r\n");
      out.write("          showuntil: 4000;\">\r\n");
      out.write("                The most<br>\r\n");
      out.write("                wanted bijouterie\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"ls-l ls-mini-text\" style=\"top: 70%; left: 60%; white-space: nowrap;\" data-ls=\"\r\n");
      out.write("          fade: true;\r\n");
      out.write("          fadeout: true;\r\n");
      out.write("          durationout: 750;\r\n");
      out.write("          easingin: easeOutQuint;\r\n");
      out.write("          delayin: 300;\r\n");
      out.write("          scalein: .8;\r\n");
      out.write("          scaleout: .8;\r\n");
      out.write("          showuntil: 4000;\">\r\n");
      out.write("                <span>Lorem ipsum and</span>\r\n");
      out.write("                <a href=\"#\">Buy It Now!</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- slide four end -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- LayerSlider end -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END SLIDER -->");
      out.write("\r\n");
      out.write("<!-- END SLIDER -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <sitemesh:write property=\"body\" />\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN BRANDS -->\r\n");
      out.write("<div class=\"brands\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"owl-carousel owl-carousel6-brands\">\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/canon.jpg\" alt=\"canon\" title=\"canon\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/esprit.jpg\" alt=\"esprit\" title=\"esprit\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/gap.jpg\" alt=\"gap\" title=\"gap\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/next.jpg\" alt=\"next\" title=\"next\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/puma.jpg\" alt=\"puma\" title=\"puma\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/zara.jpg\" alt=\"zara\" title=\"zara\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/canon.jpg\" alt=\"canon\" title=\"canon\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/esprit.jpg\" alt=\"esprit\" title=\"esprit\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/gap.jpg\" alt=\"gap\" title=\"gap\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/next.jpg\" alt=\"next\" title=\"next\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/puma.jpg\" alt=\"puma\" title=\"puma\"></a>\r\n");
      out.write("            <a href=\"shop-product-list.html\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/brands/zara.jpg\" alt=\"zara\" title=\"zara\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!-- END BRANDS -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN STEPS -->\r\n");
      out.write("<div class=\"steps-block steps-block-red\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-4 steps-block-col\">\r\n");
      out.write("                <i class=\"fa fa-truck\"></i>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Free shipping</h2>\r\n");
      out.write("                    <em>Express delivery withing 3 days</em>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span>&nbsp;</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 steps-block-col\">\r\n");
      out.write("                <i class=\"fa fa-gift\"></i>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>Daily Gifts</h2>\r\n");
      out.write("                    <em>3 Gifts daily for lucky customers</em>\r\n");
      out.write("                </div>\r\n");
      out.write("                <span>&nbsp;</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-4 steps-block-col\">\r\n");
      out.write("                <i class=\"fa fa-phone\"></i>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h2>477 505 8877</h2>\r\n");
      out.write("                    <em>24/7 customer care available</em>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!-- END STEPS -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN FOOTER -->\r\n");
      out.write("<div class=\"pre-footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- BEGIN BOTTOM ABOUT BLOCK -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("                <h2>About us</h2>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam sit nonummy nibh euismod tincidunt ut laoreet dolore magna aliquarm erat sit volutpat. Nostrud exerci tation ullamcorper suscipit lobortis nisl aliquip  commodo consequat. </p>\r\n");
      out.write("                <p>Duis autem vel eum iriure dolor vulputate velit esse molestie at dolore.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END BOTTOM ABOUT BLOCK -->\r\n");
      out.write("            <!-- BEGIN BOTTOM INFO BLOCK -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("                <h2>Information</h2>\r\n");
      out.write("                <ul class=\"list-unstyled\">\r\n");
      out.write("                    <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Delivery Information</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Customer Service</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Order Tracking</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Shipping &amp; Returns</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-angle-right\"></i> <a href=\"contacts.html\">Contact Us</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Careers</a></li>\r\n");
      out.write("                    <li><i class=\"fa fa-angle-right\"></i> <a href=\"#\">Payment Methods</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END INFO BLOCK -->\r\n");
      out.write("\r\n");
      out.write("            <!-- BEGIN TWITTER BLOCK -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("                <h2 class=\"margin-bottom-0\">Latest Tweets</h2>\r\n");
      out.write("                <a class=\"twitter-timeline\" href=\"https://twitter.com/twitterapi\" data-tweet-limit=\"2\" data-theme=\"dark\" data-link-color=\"#57C8EB\" data-widget-id=\"455411516829736961\" data-chrome=\"noheader nofooter noscrollbar noborders transparent\">Loading tweets by @keenthemes...</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END TWITTER BLOCK -->\r\n");
      out.write("\r\n");
      out.write("            <!-- BEGIN BOTTOM CONTACTS -->\r\n");
      out.write("            <div class=\"col-md-3 col-sm-6 pre-footer-col\">\r\n");
      out.write("                <h2>Our Contacts</h2>\r\n");
      out.write("                <address class=\"margin-bottom-40\">\r\n");
      out.write("                    35, Lorem Lis Street, Park Ave<br>\r\n");
      out.write("                    California, US<br>\r\n");
      out.write("                    Phone: 300 323 3456<br>\r\n");
      out.write("                    Fax: 300 323 1456<br>\r\n");
      out.write("                    Email: <a href=\"mailto:info@metronic.com\">info@metronic.com</a><br>\r\n");
      out.write("                    Skype: <a href=\"skype:metronic\">metronic</a>\r\n");
      out.write("                </address>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END BOTTOM CONTACTS -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- BEGIN SOCIAL ICONS -->\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                <ul class=\"social-icons\">\r\n");
      out.write("                    <li><a class=\"rss\" data-original-title=\"rss\" href=\"#\"></a></li>\r\n");
      out.write("                    <li><a class=\"facebook\" data-original-title=\"facebook\" href=\"#\"></a></li>\r\n");
      out.write("                    <li><a class=\"twitter\" data-original-title=\"twitter\" href=\"#\"></a></li>\r\n");
      out.write("                    <li><a class=\"googleplus\" data-original-title=\"googleplus\" href=\"#\"></a></li>\r\n");
      out.write("                    <li><a class=\"linkedin\" data-original-title=\"linkedin\" href=\"#\"></a></li>\r\n");
      out.write("                    <li><a class=\"youtube\" data-original-title=\"youtube\" href=\"#\"></a></li>\r\n");
      out.write("                    <li><a class=\"vimeo\" data-original-title=\"vimeo\" href=\"#\"></a></li>\r\n");
      out.write("                    <li><a class=\"skype\" data-original-title=\"skype\" href=\"#\"></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END SOCIAL ICONS -->\r\n");
      out.write("            <!-- BEGIN NEWLETTER -->\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                <div class=\"pre-footer-subscribe-box pull-right\">\r\n");
      out.write("                    <h2>Newsletter</h2>\r\n");
      out.write("                    <form action=\"#\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"text\" placeholder=\"youremail@mail.com\" class=\"form-control\">\r\n");
      out.write("                            <span class=\"input-group-btn\">\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\">Subscribe</button>\r\n");
      out.write("                  </span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END NEWLETTER -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- BEGIN COPYRIGHT -->\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 padding-top-10\">\r\n");
      out.write("                2014 Â© Metronic Shop UI. ALL Rights Reserved.\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END COPYRIGHT -->\r\n");
      out.write("            <!-- BEGIN PAYMENTS -->\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6\">\r\n");
      out.write("                <ul class=\"list-unstyled list-inline pull-right\">\r\n");
      out.write("                    <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/img/payments/western-union.jpg\" alt=\"We accept Western Union\" title=\"We accept Western Union\"></li>\r\n");
      out.write("                    <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/img/payments/american-express.jpg\" alt=\"We accept American Express\" title=\"We accept American Express\"></li>\r\n");
      out.write("                    <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/img/payments/MasterCard.jpg\" alt=\"We accept MasterCard\" title=\"We accept MasterCard\"></li>\r\n");
      out.write("                    <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/img/payments/PayPal.jpg\" alt=\"We accept PayPal\" title=\"We accept PayPal\"></li>\r\n");
      out.write("                    <li><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/img/payments/visa.jpg\" alt=\"We accept Visa\" title=\"We accept Visa\"></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- END PAYMENTS -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("<!-- END FOOTER -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN fast view of a product -->\r\n");
      out.write("<div id=\"product-pop-up\" style=\"display: none; width: 700px;\">\r\n");
      out.write("    <div class=\"product-page product-pop-up\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-3\">\r\n");
      out.write("                <div class=\"product-main-image\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model7.jpg\" alt=\"Cool green dress with red bell\" class=\"img-responsive\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-other-images\">\r\n");
      out.write("                    <a href=\"#\" class=\"active\"><img alt=\"Berry Lace Dress\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model3.jpg\"></a>\r\n");
      out.write("                    <a href=\"#\"><img alt=\"Berry Lace Dress\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\"></a>\r\n");
      out.write("                    <a href=\"#\"><img alt=\"Berry Lace Dress\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model5.jpg\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 col-sm-6 col-xs-9\">\r\n");
      out.write("                <h2>Cool green dress with red bell</h2>\r\n");
      out.write("                <div class=\"price-availability-block clearfix\">\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                        <strong><span>$</span>47.00</strong>\r\n");
      out.write("                        <em>$<span>62.00</span></em>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"availability\">\r\n");
      out.write("                        Availability: <strong>In Stock</strong>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"description\">\r\n");
      out.write("                    <p>Lorem ipsum dolor ut sit ame dolore  adipiscing elit, sed nonumy nibh sed euismod laoreet dolore magna aliquarm erat volutpat\r\n");
      out.write("                        Nostrud duis molestie at dolore.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-page-options\">\r\n");
      out.write("                    <div class=\"pull-left\">\r\n");
      out.write("                        <label class=\"control-label\">Size:</label>\r\n");
      out.write("                        <select class=\"form-control input-sm\">\r\n");
      out.write("                            <option>L</option>\r\n");
      out.write("                            <option>M</option>\r\n");
      out.write("                            <option>XL</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"pull-left\">\r\n");
      out.write("                        <label class=\"control-label\">Color:</label>\r\n");
      out.write("                        <select class=\"form-control input-sm\">\r\n");
      out.write("                            <option>Red</option>\r\n");
      out.write("                            <option>Blue</option>\r\n");
      out.write("                            <option>Black</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-page-cart\">\r\n");
      out.write("                    <div class=\"product-quantity\">\r\n");
      out.write("                        <input id=\"product-quantity\" type=\"text\" value=\"1\" readonly name=\"product-quantity\" class=\"form-control input-sm\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\">Add to cart</button>\r\n");
      out.write("                    <a href=\"shop-item.html\" class=\"btn btn-default\">More details</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"sticker sticker-sale\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END fast view of a product -->\r\n");
      out.write("\r\n");
      out.write("<!-- Load javascripts at bottom, this will reduce page load time -->\r\n");
      out.write("<!-- BEGIN CORE PLUGINS (REQUIRED FOR ALL PAGES) -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/respond.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/jquery-migrate.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/scripts/back-to-top.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- END CORE PLUGINS -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN PAGE LEVEL JAVASCRIPTS (REQUIRED ONLY FOR CURRENT PAGE) -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/fancybox/source/jquery.fancybox.pack.js\" type=\"text/javascript\"></script><!-- pop up -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/carousel-owl-carousel/owl-carousel/owl.carousel.min.js\" type=\"text/javascript\"></script><!-- slider for products -->\r\n");
      out.write("<script src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/zoom/jquery.zoom.min.js' type=\"text/javascript\"></script><!-- product zoom -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/bootstrap-touchspin/bootstrap.touchspin.js\" type=\"text/javascript\"></script><!-- Quantity -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/uniform/jquery.uniform.min.js\" type=\"text/\r\n");
      out.write("<!-- BEGIN LayerSlider -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/slider-layer-slider/js/greensock.js\" type=\"text/javascript\"></script><!-- External libraries: GreenSock -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/slider-layer-slider/js/layerslider.transitions.js\" type=\"text/javascript\"></script><!-- LayerSlider script files -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/global/plugins/slider-layer-slider/js/layerslider.kreaturamedia.jquery.js\" type=\"text/javascript\"></script><!-- LayerSlider script files -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/scripts/layerslider-init.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- END LayerSlider -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/layout/scripts/layout.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    jQuery(document).ready(function() {\r\n");
      out.write("        Layout.init();\r\n");
      out.write("        Layout.initOWL();\r\n");
      out.write("        LayersliderInit.initLayerSlider();\r\n");
      out.write("        Layout.initImageZoom();\r\n");
      out.write("        Layout.initTouchspin();\r\n");
      out.write("        Layout.initTwitter();\r\n");
      out.write("        Layout.initUniform()\r\n");
      out.write("        Layout.initFixHeaderWithPreHeader();\r\n");
      out.write("        Layout.initNavScrolling();\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("<!-- END PAGE LEVEL JAVASCRIPTS -->\r\n");
      out.write("</body>\r\n");
      out.write("<!-- END BODY -->\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/decorators/web.jsp(2,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/");
      // /WEB-INF/decorators/web.jsp(2,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("URL");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /commons/web/header.jsp(36,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.account == null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/login\">Login</a>\r\n");
          out.write("                    | <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/register\">Register</a>\r\n");
          out.write("                </ul>\r\n");
          out.write("                </div>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myaccount\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a> |\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/logout\">Logout</a>\r\n");
          out.write("            </div>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
