/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-09-30 03:16:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- BEGIN SALE PRODUCT & NEW ARRIVALS -->\r\n");
      out.write("<div class=\"row margin-bottom-40\">\r\n");
      out.write("    <!-- BEGIN SALE PRODUCT -->\r\n");
      out.write("    <div class=\"col-md-12 sale-product\">\r\n");
      out.write("        <h2>New Arrivals</h2>\r\n");
      out.write("        <div class=\"owl-carousel owl-carousel5\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                    <div class=\"sticker sticker-sale\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress2</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model6.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model6.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress2</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"#\">Berry Lace Dress4</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                    <div class=\"sticker sticker-new\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model5.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model5.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress5</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress3</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model7.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/model7.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress3</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- END SALE PRODUCT -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END SALE PRODUCT & NEW ARRIVALS -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN SIDEBAR & CONTENT -->\r\n");
      out.write("<div class=\"row margin-bottom-40 \">\r\n");
      out.write("    <!-- BEGIN SIDEBAR -->\r\n");
      out.write("    <div class=\"sidebar col-md-3 col-sm-4\">\r\n");
      out.write("        <ul class=\"list-group margin-bottom-25 sidebar-menu\">\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Ladies</a></li>\r\n");
      out.write("            <li class=\"list-group-item clearfix dropdown\">\r\n");
      out.write("                <a href=\"shop-product-list.html\">\r\n");
      out.write("                    <i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("                    Mens\r\n");
      out.write("\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"dropdown-menu\">\r\n");
      out.write("                    <li class=\"list-group-item dropdown clearfix\">\r\n");
      out.write("                        <a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Shoes </a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                            <li class=\"list-group-item dropdown clearfix\">\r\n");
      out.write("                                <a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Classic </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Classic 1</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Classic 2</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"list-group-item dropdown clearfix\">\r\n");
      out.write("                                <a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sport  </a>\r\n");
      out.write("                                <ul class=\"dropdown-menu\">\r\n");
      out.write("                                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sport 1</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sport 2</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Trainers</a></li>\r\n");
      out.write("                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Jeans</a></li>\r\n");
      out.write("                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Chinos</a></li>\r\n");
      out.write("                    <li><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> T-Shirts</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Kids</a></li>\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Accessories</a></li>\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Sports</a></li>\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Brands</a></li>\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Electronics</a></li>\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Home & Garden</a></li>\r\n");
      out.write("            <li class=\"list-group-item clearfix\"><a href=\"shop-product-list.html\"><i class=\"fa fa-angle-right\"></i> Custom Link</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- END SIDEBAR -->\r\n");
      out.write("    <!-- BEGIN CONTENT -->\r\n");
      out.write("    <div class=\"col-md-9 col-sm-8\">\r\n");
      out.write("        <h2>Three items</h2>\r\n");
      out.write("        <div class=\"owl-carousel owl-carousel3\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                    <div class=\"sticker sticker-new\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress2</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress3</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress4</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                    <div class=\"sticker sticker-sale\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress5</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress6</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- END CONTENT -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END SIDEBAR & CONTENT -->\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN TWO PRODUCTS & PROMO -->\r\n");
      out.write("<div class=\"row margin-bottom-35 \">\r\n");
      out.write("    <!-- BEGIN TWO PRODUCTS -->\r\n");
      out.write("    <div class=\"col-md-6 two-items-bottom-items\">\r\n");
      out.write("        <h2>Two items</h2>\r\n");
      out.write("        <div class=\"owl-carousel owl-carousel2\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k2.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k1.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k4.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"product-item\">\r\n");
      out.write("                    <div class=\"pi-img-wrapper\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/products/k3.jpg\" class=\"btn btn-default fancybox-button\">Zoom</a>\r\n");
      out.write("                            <a href=\"#product-pop-up\" class=\"btn btn-default fancybox-fast-view\">View</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3><a href=\"shop-item.html\">Berry Lace Dress</a></h3>\r\n");
      out.write("                    <div class=\"pi-price\">$29.00</div>\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-default add2cart\">Add to cart</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- END TWO PRODUCTS -->\r\n");
      out.write("    <!-- BEGIN PROMO -->\r\n");
      out.write("    <div class=\"col-md-6 shop-index-carousel\">\r\n");
      out.write("        <div class=\"content-slider\">\r\n");
      out.write("            <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("                <!-- Indicators -->\r\n");
      out.write("                <ol class=\"carousel-indicators\">\r\n");
      out.write("                    <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("                    <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("                    <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("                </ol>\r\n");
      out.write("                <div class=\"carousel-inner\">\r\n");
      out.write("                    <div class=\"item active\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/index-sliders/slide1.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/index-sliders/slide2.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"item\">\r\n");
      out.write("                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/frontend/pages/img/index-sliders/slide3.jpg\" class=\"img-responsive\" alt=\"Berry Lace Dress\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- END PROMO -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END TWO PRODUCTS & PROMO -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
